---
name: Documentation
on:
  workflow_call:
    inputs:
      fqcn:
        required: true
        type: string
      collection_fqcn:
        required: true
        type: string
      historical_docs:
        required: false
        type: string
        default: 'true'

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      packages: write
      pages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{ inputs.fqcn }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ansible_collections/${{ inputs.fqcn }}/docs/requirements.txt ]; then
            pip install -r ansible_collections/${{ inputs.fqcn }}/docs/requirements.txt
          fi
          if [ -f ansible_collections/${{ inputs.fqcn }}/requirements.txt ]; then
            pip install -r ansible_collections/${{ inputs.fqcn }}/requirements.txt
          fi
          sudo apt --fix-missing update
          sudo apt install -y sed hub

      - name: Create default collection path
        run: |
          mkdir -p /home/runner/.ansible/
          ln -s ${{ github.workspace }} /home/runner/.ansible/collections

      - name: Create changelog and documentation
        uses: ansible-middleware/collection-docs-action@main
        with:
          collection_fqcn: ${{ inputs.collection_fqcn }}
          collection_repo: ${{ github.repository }}
          dependencies: false
          commit_changelog: false
          commit_ghpages: true
          changelog_release: false
          generate_docs: true
          path: ansible_collections/${{ inputs.fqcn }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot_email: ansible-middleware-core@redhat.com
          bot_account: ansible-middleware-core
          historical_docs: ${{ inputs.historical_docs }}

